"""Add DOCX storage fields to templates

Revision ID: f2cafb42bb42
Revises:
Create Date: 2025-09-23 15:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2cafb42bb42'
down_revision = '0006_update_templates'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('templates', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('templates', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('templates', sa.Column('mime_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'mime_type')
    op.drop_column('templates', 'file_size')
    op.drop_column('templates', 'file_name')
    op.drop_column('templates', 'file_path')
    # ### end Alembic commands ###