export const paths = {
  home: '/',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password' },
  dashboard: {
    overview: '/dashboard',
    account: '/dashboard/account',
    users: '/dashboard/users',
    createUser: '/dashboard/users/create',
    editUser: (userId: number) => `/dashboard/users/${userId}/edit`,
    clients: '/dashboard/clients',
    createClient: '/dashboard/clients/create',
    editClient: (clientId: number) => `/dashboard/clients/${clientId}/edit`,
    partners: '/dashboard/partners',
    createPartner: '/dashboard/partners/create',
    editPartner: (partnerId: number) => `/dashboard/partners/${partnerId}/edit`,
    templates: '/dashboard/templates',
    quotations: '/dashboard/quotations',
    createQuotation: '/dashboard/quotations/create',
    editQuotation: (quotationId: number) => `/dashboard/quotations/${quotationId}/edit`,
    invoices: '/dashboard/invoices',
    createInvoice: '/dashboard/invoices/create',
    editInvoice: (invoiceId: number) => `/dashboard/invoices/${invoiceId}/edit`,
    emails: '/dashboard/emails',
    emailsSend: '/dashboard/emails/send',
    emailsHistory: '/dashboard/emails/history',
    emailsScheduled: '/dashboard/emails/scheduled',
    emailsTemplates: '/dashboard/emails/templates',
    emailsAutomation: '/dashboard/emails/automation',
    emailsSettings: '/dashboard/emails/settings',
    companySettings: '/dashboard/company-settings',
    settings: '/dashboard/settings',
  },
  errors: { notFound: '/errors/not-found' },
} as const;
